name: genbadge
on:
  push:
    branches: [ "master" ]
jobs:
  run_all_tests:
    runs-on: ubuntu-latest
    name: Create badges
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[tests]
          python -m pip install genbadge[all]
      - name: Launch tests & generate badge
        run: |
          python -m pytest
          genbadge tests --output-file=reports/junit/tests-badge.svg
          genbadge coverage --output-file=reports/coverage/coverage-badge.svg
      - name: Lint with flake8
        run: |
          flake8 src tests --count --exit-zero --statistics --max-complexity=10 --format=html --htmldir=reports/flake8 --output-file=reports/flake8/flake8stats.txt
          genbadge flake8 --output-file=reports/flake8/flake8-badge.svg
      - name: remove coverage html .gitignore
        run: rm -f reports/coverage/html/.gitignore
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: reports
          FOLDER: reports
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
